config/routes.rb
Pairser::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin_gem', :as => 'rails_admin'
  root 'pages#index'

  resources :site_errors
  resources :parse_requests
  resources :images

  resources :goods do
    member do
      get 'view'
    end
    collection do
      get 'my'
    end
  end

  resources :sites do
    collection do
      post 'parse'
    end
  end

  match 'admin' => 'pages#admin', via: :get

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/parse_request.rb
# User requests to add instructions to website. Created during url parsing when there is no instruction for website
# @example
#   #<ParseRequest id: 1, domain: "github.com", count: 1, created_at: "2014-03-25 16:21:13", updated_at: "2014-03-25 16:21:14">

class ParseRequest < ActiveRecord::Base
  include AdminCount
  validates :domain, presence: true
end

app/controllers/parse_requests_controller.rb
class ParseRequestsController < ApplicationController
  include Access
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy, :index, :show]
  before_action :set_parse_request, only: [:show, :edit, :update, :destroy]

  # GET /parse_requests
  # GET /parse_requests.json
  def index
    @parse_requests = ParseRequest.all
  end

  # GET /parse_requests/1
  # GET /parse_requests/1.json
  def show
  end

  # GET /parse_requests/new
  def new
    @parse_request = ParseRequest.new
  end

  # GET /parse_requests/1/edit
  def edit
  end

  # POST /parse_requests
  # POST /parse_requests.json
  def create
    @parse_request = ParseRequest.new(parse_request_params)

    respond_to do |format|
      if @parse_request.save
        format.html { redirect_to @parse_request, notice: 'Parse request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parse_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @parse_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parse_requests/1
  # PATCH/PUT /parse_requests/1.json
  def update
    respond_to do |format|
      if @parse_request.update(parse_request_params)
        format.html { redirect_to @parse_request, notice: 'Parse request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parse_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parse_requests/1
  # DELETE /parse_requests/1.json
  def destroy
    @parse_request.destroy
    respond_to do |format|
      format.html { redirect_to parse_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parse_request
      @parse_request = ParseRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parse_request_params
      params.require(:parse_request).permit(:domain, :count)
    end
end

app/views/parse_requests/_form.html.haml
= form_for @parse_request, :html => { :class => 'form-horizontal form-model' } do |f|
  - if @parse_request.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = @parse_request.errors.count
      %ul
        - @parse_request.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :domain, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :domain, :class => 'text-field form-control'
  .form-group
    = f.label :count, :class => 'control-label col-md-2'
    .col-md-10
      = f.number_field :count, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'

app/views/parse_requests/edit.html.haml
- model_class = ParseRequest
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ParseRequest
= render :partial => 'form'

app/views/parse_requests/index.html.haml
.page-header
  %h1 Запросы на добавление сайтов
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th domain
      %th count
      %th updated_at
      %th действия
  %tbody
    - @parse_requests.each do |parse_request|
      %tr
        %td= parse_request.id
        %td= parse_request.domain
        %td= parse_request.count
        %td= l parse_request.updated_at, format: :long
        %td
          =link_to "редактировать", edit_parse_request_path(parse_request.id)
        %td
          =link_to "удалить", parse_request, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete
= link_to 'Новый', new_parse_request_path, :class => 'btn btn-primary'

app/views/parse_requests/new.html.haml
- model_class = ParseRequest
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ParseRequest
= render :partial => 'form'

app/views/parse_requests/show.html.haml
- model_class = ParseRequest
.page-header
  %h1= t '.title', :default => ParseRequest
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:domain)
    %dd
      %pre.prettyprint= @parse_request.domain
    %dt.label.label-default= model_class.human_attribute_name(:count)
    %dd
      %pre.prettyprint= @parse_request.count
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    parse_requests_path, :class => 'btn btn-default'         |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")),             |
    edit_parse_request_path(@parse_request), :class => 'btn btn-default' |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    parse_request_path(@parse_request),                                                                          |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |