config/routes.rb
Pairser::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin_gem', :as => 'rails_admin'
  root 'pages#index'

  resources :site_errors
  resources :parse_requests
  resources :images

  resources :goods do
    member do
      get 'view'
    end
    collection do
      get 'my'
    end
  end

  resources :sites do
    collection do
      post 'parse'
    end
  end

  match 'admin' => 'pages#admin', via: :get

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_flash.haml
- flash.each do |type, message|
  %div{class: "alert #{alert_class_for(type)} alert-dismissable fade in"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    = message

app/views/elements/_left_nav.haml
.navbar-header
  = link_to "Pairser", root_path, class: "navbar-brand"
  %ul.nav.navbar-nav
    - if user_signed_in?
      %li= link_to "Мои вещи", my_goods_path
      - if current_user.admin?
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Админское
            %b.caret
          %ul.dropdown-menu
            %li= link_to "Админка", admin_path
            %li.divider
            %li= link_to "Добавить сайт", new_site_url
            %li= link_to "Запросы на инструкцию", parse_requests_path
            %li= link_to "Ошибки парсинга", site_errors_path
            %li= link_to "Товары", goods_path
            %li= link_to "Сайты", sites_path
            %li= link_to "Изображения", images_path

app/views/elements/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    = render 'elements/left_nav'
    = render 'elements/right_nav'

app/views/elements/_right_nav.haml
#navbar-collapse-1.collapse.navbar-collapse
  %ul.nav.navbar-nav.navbar-right
    - if user_signed_in?
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Аккаунт
          %b.caret
        %ul.dropdown-menu
          %li= link_to "Настройки", edit_user_registration_path
          %li.divider
          %li= link_to "Выйти", destroy_user_session_path, method: :delete
    - else
      %li= link_to "Войти", new_user_session_path
      %li= link_to "Зарегистрироваться", new_user_registration_path