config/routes.rb
Pairser::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin_gem', :as => 'rails_admin'
  root 'pages#index'

  resources :site_errors
  resources :parse_requests
  resources :images

  resources :goods do
    member do
      get 'view'
    end
    collection do
      get 'my'
    end
  end

  resources :sites do
    collection do
      post 'parse'
    end
  end

  match 'admin' => 'pages#admin', via: :get

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/good.rb
# Goods. They are created when parsed from url
# @example
#   #<Good id: 1, name: "FlyKnit Lunar1+ sneakers", main_image_id: 1, created_at: "2014-03-25 14:19:36", updated_at: "2014-03-25 14:19:36", user_id: 1>
class Good < ActiveRecord::Base
  has_many :images
  has_one :main_image, class_name: 'Image'
  belongs_to :user

  validates :user_id, presence: true

  # Gets url of goods' main image
  # @note is called in good' view
  # @example
  #   url = Good.first.get_main_image_website
  # @return [String] url of good' main image
  def get_main_image_website
    Image.find(self.main_image_id).website
  end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  include Access
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy, :show, :index]
  before_action :require_user_signed_in, only: [:my]
  before_action :set_good, only: [:show, :edit, :update, :destroy, :view]

  # List of user' goods
  # @note user must be signed_in
  # GET /goods/my
  def my
    @my_goods = current_user.goods
  end

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end


  # User-friendly view of good
  # @note GET /goods/1/view
  # @note sortes images so that main one is first
  def view
    if belongs_to_user?(@good)
      @good_images = [@good.main_image] + Image.ad_images_of_good(@good)
      @good_images.flatten!
    else
      redirect_to root_path, alert: 'Это не ваша сохраненная вещь'
    end
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render action: 'show', status: :created, location: @good }
      else
        format.html { render action: 'new' }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :main_image_id, :user_id)
    end
end

app/views/goods/_form.html.haml
= form_for @good, :html => { :class => 'form-horizontal' } do |f|
  - if @good.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = @good.errors.count
      %ul
        - @good.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, :class => 'text-field form-control'
  .form-group
    = f.label :main_image_id, :class => 'control-label col-md-2'
    .col-md-10
      = f.number_field :main_image_id, :class => 'text-field form-control'
  .form-group
    = f.label :user_id, :class => 'control-label col-md-2'
    .col-md-10
      = f.number_field :user_id, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'          |

app/views/goods/_good.haml
%article.good_block{data: {link: view_good_path(good.id)}}
  =image_tag good.get_main_image_website
  %h4
    =good.name

app/views/goods/edit.html.haml
.page-header
  %h1 Редактировать
= render 'form'

app/views/goods/index.html.haml
.page-header
  %h1 Товар
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th name
      %th website
      %th main_image_id
      %th User_id
      %th created_at
      %th действия
  %tbody
    - @goods.each do |good|
      %tr
        %td= good.id
        %td= good.name
        %td= good.website
        %td= good.main_image_id
        %td= good.user_id
        %td= l good.created_at, format: :long
        %td
          =link_to "редактировать", edit_good_path(good.id)
        %td
          =link_to "удалить", good, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete
= link_to 'Создать', |
  new_good_path,                                         |
  :class => 'btn btn-primary'                            |

app/views/goods/my.haml
.page-header
  %h1 Мои вещи

.container#my_goods
  -if @my_goods.blank?
    =link_to "Добавь", root_path
    вещи в свой список, чтобы смотреть их здесь.
  =render @my_goods

app/views/goods/new.html.haml
.page-header
  %h1 Новый товар
= render 'form'

app/views/goods/show.html.haml
- model_class = Good
.page-header
  %h1= t '.title', :default => Good
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:name)
    %dd
      %pre.prettyprint= @good.name
    %dt.label.label-default= model_class.human_attribute_name(:main_image_id)
    %dd
      %pre.prettyprint= @good.main_image_id
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    goods_path, :class => 'btn btn-default'                  |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_good_path(@good), :class => 'btn btn-default'       |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    good_path(@good),                                                                                            |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |

app/views/goods/view.haml
#good_view
  %h1
    =link_to @good.name, @good.website, target: "_blank"

  =render partial: 'goods/view/carousel', locals: {good_images: @good_images}