config/routes.rb
Pairser::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin_gem', :as => 'rails_admin'
  root 'pages#index'

  resources :site_errors
  resources :parse_requests
  resources :images

  resources :goods do
    member do
      get 'view'
    end
    collection do
      get 'my'
    end
  end

  resources :sites do
    collection do
      post 'parse'
    end
  end

  match 'admin' => 'pages#admin', via: :get

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/site_error.rb
# A website instruction for parser. Created by admin
# @example
#   #<Site id: 1, domain: "net-a-porter.com", name_selector: "#product-details h1", main_image_selector: "#medium-image", images_selector: "", button_selector: "#thumbnails-container img", created_at: "2014-03-25 14:19:37", updated_at: "2014-03-25 14:19:37">

class SiteError < ActiveRecord::Base
  include AdminCount
end

app/controllers/site_errors_controller.rb
# Site errors admin actions
class SiteErrorsController < ApplicationController
  before_action :set_site_error, only: [:show, :edit, :update, :destroy]

  # GET /site_errors
  # GET /site_errors.json
  def index
    @site_errors = SiteError.all
  end

  # GET /site_errors/1
  # GET /site_errors/1.json
  def show
  end

  # GET /site_errors/new
  def new
    @site_error = SiteError.new
  end

  # GET /site_errors/1/edit
  def edit
  end

  # POST /site_errors
  # POST /site_errors.json
  def create
    @site_error = SiteError.new(site_error_params)

    respond_to do |format|
      if @site_error.save
        format.html { redirect_to @site_error, notice: 'Site error was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site_error }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_errors/1
  # PATCH/PUT /site_errors/1.json
  def update
    respond_to do |format|
      if @site_error.update(site_error_params)
        format.html { redirect_to @site_error, notice: 'Site error was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_errors/1
  # DELETE /site_errors/1.json
  def destroy
    @site_error.destroy
    respond_to do |format|
      format.html { redirect_to site_errors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_error
      @site_error = SiteError.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_error_params
      params.require(:site_error).permit(:domain)
    end
end

app/views/site_errors/_form.html.haml
= form_for @site_error, :html => { :class => 'form-horizontal form-model' } do |f|
  - if @site_error.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = @site_error.errors.count
      %ul
        - @site_error.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :domain, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :domain, :class => 'text-field form-control'
  .form-group
    = f.label :count, :class => 'control-label col-md-2'
    .col-md-10
      = f.number_field :count, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'

app/views/site_errors/edit.html.haml
%h1 Editing site_error
= render 'form'
= link_to 'Show', @site_error
|
\#{link_to 'Back', site_errors_path}

app/views/site_errors/index.html.haml
.page-header
  %h1 Ошибки парсинга
%table.table.table-striped
  %thead
    %tr
      %th Domain
      %th count
      %th
      %th
      %th
  %tbody
    - @site_errors.each do |site_error|
      %tr
        %td= site_error.domain
        %td= site_error.count
        %td= link_to 'Show', site_error
        %td= link_to 'Edit', edit_site_error_path(site_error)
        %td= link_to 'Destroy', site_error, method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'Новый', new_site_error_path, :class => 'btn btn-primary'

app/views/site_errors/new.html.haml
%h1 New site_error
= render 'form'
= link_to 'Back', site_errors_path

app/views/site_errors/show.html.haml
%p#notice= notice
%p
  %strong Domain:
  = @site_error.domain
= link_to 'Edit', edit_site_error_path(@site_error)
|
\#{link_to 'Back', site_errors_path}